<?php

use App\Models\SiteSetting;
use App\Models\User;
use Inertia\Testing\AssertableInertia as Assert;

beforeEach(function () {
    // Generated by Google Maps Share > Embed a map for the existing resort pin.
    $parameters = '!1m17!1m12!1m3!1d3868.435301613417!2d121.20333287509796!3d14.169263686267556!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m2!1m1!2zMTTCsDEwJzA5LjQiTiAxMjHCsDEyJzIxLjMiRQ!5e0!3m2!1sen!2sph!4v1788880557221!5m2!1sen!2sph';
    $this->embedUrl = 'https://www.google.com/maps/embed?pb='.$parameters;
    $this->normalizedEmbedUrl = 'https://www.google.com/maps/embed?pb='.rawurlencode($parameters);
});

test('admin can save a Google-generated map embed URL or copied iframe HTML', function (bool $asHtml) {
    $input = $asHtml ? '<iframe src="'.$this->embedUrl.'" width="600" onload="alert(1)"></iframe>' : $this->embedUrl;

    $this->actingAs(User::factory()->create(['role' => 'admin']))
        ->post(route('admin.landing-page.update', 'contact'), ['map_embed_url' => $input])
        ->assertRedirect()->assertSessionHasNoErrors();

    expect(SiteSetting::where('section', 'contact')->sole()->map_embed_url)->toBe($this->normalizedEmbedUrl);
    $this->get(route('admin.landing-page.index'))->assertInertia(fn (Assert $page) => $page
        ->where('contact.map_embed_url', $this->normalizedEmbedUrl));

    auth()->logout();
    $this->get('/')->assertOk()->assertInertia(fn (Assert $page) => $page
        ->where('contact.map_embed_url', $this->normalizedEmbedUrl));
})->with([false, true]);

test('invalid map links cannot replace a working embed', function (mixed $input) {
    $contact = SiteSetting::create(['section' => 'contact', 'map_embed_url' => $this->normalizedEmbedUrl]);

    $this->actingAs(User::factory()->create(['role' => 'admin']))
        ->post(route('admin.landing-page.update', 'contact'), ['map_embed_url' => $input])
        ->assertSessionHasErrors('map_embed_url');

    expect($contact->refresh()->map_embed_url)->toBe($this->normalizedEmbedUrl);
})->with([
    'legacy coordinate search' => ['https://www.google.com/maps?q=14.169263671507453,121.20590780053948&output=embed'],
    'regular map search' => ['https://www.google.com/maps/search/Q8+Private+Resort'],
    'short share link' => ['https://maps.app.goo.gl/example'],
    'missing embed parameters' => ['https://www.google.com/maps/embed'],
    'invalid parameter type' => ['https://www.google.com/maps/embed?pb[]=invalid'],
    'insecure scheme' => ['http://www.google.com/maps/embed?pb=!1m17'],
    'unsafe URL' => ['javascript:alert(1)'],
    'wrong host' => ['https://www.google.com.evil.test/maps/embed?pb=!1m17'],
    'URL credentials' => ['https://evil.test@www.google.com/maps/embed?pb=!1m17'],
    'unsafe iframe' => ['<iframe src="https://evil.test"></iframe>'],
    'HTML without an iframe' => ['<script>alert(1)</script>'],
    'invalid type' => [['invalid' => 'value']],
]);

test('contact edits retain the existing map unless it is explicitly cleared', function () {
    $contact = SiteSetting::create(['section' => 'contact', 'map_embed_url' => $this->normalizedEmbedUrl]);
    $this->actingAs(User::factory()->create(['role' => 'admin']))
        ->post(route('admin.landing-page.update', 'contact'), ['title' => 'Contact us'])
        ->assertSessionHasNoErrors();
    expect($contact->refresh()->map_embed_url)->toBe($this->normalizedEmbedUrl);

    $this->post(route('admin.landing-page.update', 'contact'), ['map_embed_url' => ''])
        ->assertSessionHasNoErrors();
    expect($contact->refresh()->map_embed_url)->toBeNull();
    $this->get('/')->assertInertia(fn (Assert $page) => $page->where('contact.map_embed_url', null));
});

test('an unsafe legacy URL is not rendered inside the public map iframe', function () {
    SiteSetting::create(['section' => 'contact', 'map_embed_url' => 'https://evil.test']);

    $this->get('/')->assertOk()->assertInertia(fn (Assert $page) => $page->where('contact.map_embed_url', null));
});
